# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kdahlborn
# "service" is the name of this project. This will also be added to your AWS resource names.
service: streaming-service

provider:
    name: aws
    runtime: nodejs24.x
    architecture: arm64
    region: eu-north-1
    iam:
        role: ${file(./config.yml):role}

functions:
    ## SERIES
    getSeries:
        handler: functions/series/getSeries/index.handler
        events:
            - httpApi:
                  path: /series/{seriesId}
                  method: GET
    getSeriesContent:
        handler: functions/series/getSeriesContent/index.handler
        events:
            - httpApi:
                  path: /series/{seriesId}/content
                  method: GET

    ## EPISODES
    getEpisodes:
        handler: functions/episodes/getEpisodes/index.handler
        events:
            - httpApi:
                  path: /series/{seriesId}/seasons/{season}
                  method: GET
    addNewEpisode:
        handler: functions/episodes/addNewEpisode/index.handler
        events:
            - httpApi:
                  path: /series/{seriesId}/seasons/{season}/episodes
                  method: POST
    updateEpisode:
        handler: functions/episodes/updateEpisode/index.handler
        events:
            - httpApi:
                  path: /series/{seriesId}/seasons/{season}/episodes/{episode}
                  method: PUT
